name: cypress
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: ./
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:8080'
