name: e2e
on: [push]
jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [2]
        ci_node_index: [0, 1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          parallel: true
          record: true
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          env: GRAPHCMS_PREVIEW_SECRET=${{ secrets.GRAPHCMS_PREVIEW_SECRET }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRAPHCMS_API: ${{ secrets.GRAPHCMS_API }}
          GRAPHCMS_TOKEN: ${{ secrets.GRAPHCMS_TOKEN }}
          GRAPHCMS_PREVIEW_SECRET: ${{ secrets.GRAPHCMS_PREVIEW_SECRET }}
