name: e2e
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          parallel: true
          record: true
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRAPHCMS_API: ${{ secrets.GRAPHCMS_API }}
          GRAPHCMS_TOKEN: ${{ secrets.GRAPHCMS_TOKEN }}
