name: tests
on: [push]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run unit tests
        run: yarn test
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          parallel: true
          record: true
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRAPHCMS_API: ${{ secrets.GRAPHCMS_API }}
          GRAPHCMS_TOKEN: ${{ secrets.GRAPHCMS_TOKEN }}
